# ----------- CONFIGURABLE START -----------
title:            "boom妒忌噶 blog"
description:      "欢迎来到 boom妒忌噶「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              https://zhangjinbo619.github.io # 域名
signoff:          "boom妒忌噶" # Your name
facebook_appid:   #liberxue
google_analytics: UA-119669912-1 #ga
baidu_analytics: 7184bba00833160395ef250c99784aef #百度统计
share: true 
#### Exclude
#exclude: ["vendor"]
# 分页
paginate: 15
paginate_path: "boompage:num"
#云数据库
leancloud:
  enable: true
  app_id: bxCEeIyMwxY90tWj3BKYKWfO-gzGzoHsz
  app_key: pM2T2UQ6L8G38MtAA5s2HJ0A

gems: [jekyll-paginate]

links:
  - name:         首页
    url:          /
    external:     false
  - name:         随笔
    url:          /book
    external:     false
  - name:         技术
    url:          /tech
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink:  /:categories/:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
